Roadmap plan create route
uCredit-Dev/uCredit-API pull request #46
Opened 2022-07-29 00:49 UTC by Matth-ewe-f

Route to create a roadmap plan given a plan (non-roadmap) to copy. Currently does not copy distribution sub-documents as they're not being used. Tested with Postman and MongoDB Compass by visually inspecting results

2022-08-04 02:30 UTC, QinyuanWu commented
can a user remove a roadmap plan?

2022-08-04 02:33 UTC, QinyuanWu commented on routes/roadmapPlan.js
>    const old_id = req.body.id;
Please use more specific naming and specify the type of id(e.g. plan_id)

2022-08-04 02:33 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +  const desc = req.body.desc;
roadmap_description

2022-08-04 02:34 UTC, QinyuanWu commented on routes/roadmapPlan.js
>        let data = {
original_plan, roadmap_data

2022-08-04 02:34 UTC, QinyuanWu commented on routes/roadmapPlan.js
>      .findById(old_id)
original_plan_id

2022-08-04 02:35 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +        num_likes: 0,
another option is to change the Roadmap schema to have a default value for this field

2022-08-04 02:37 UTC, QinyuanWu commented on routes/roadmapPlan.js
>          tags: [],
can a user provide tags?

2022-08-04 02:40 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +      let yearPromise = Promise.all(
what is a yearPromise?

2022-08-04 02:42 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +        retrieved.year_ids.map(async (elem) => {
year_id instead of elem

2022-08-04 02:44 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +          let found = await years.find({ _id: elem }, { _id: 0 });
why are there two _id? can you use the fineById method

2022-08-04 02:44 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +      await Promise.all([yearPromise]); // add distPromise when applicable
what is distPromise, and when is it applicable?

2022-08-04 02:46 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +const yearNameToArrIndex = (name) => {
what's the purpose of this helpermethod

2022-08-04 02:47 UTC, QinyuanWu commented on routes/roadmapPlan.js
>  router.get("/api/roadmapPlans/get/:plan_id", (req, res) => {
"/api/roadmapPlans/get/:roadmapPlan_id" plan and roadmapPlan are distinct schemas

2022-08-04 02:47 UTC, QinyuanWu commented on routes/roadmapPlan.js
> +        await Promise.all(
what is happening here

2022-08-04 02:56 UTC, QinyuanWu requested changes
General comments:
can a user remove a roadmap plan? There is no delete route
the tag field is set to [] when creating a roadmap. can a user assign tags when they upload a roadmap? I don't see a route where the tags can be updated
Suggestions:
in the Roadmap schema, change original to original_plan_id
assign more specific names to variables. details see in code comments
modularize the code and reduce number of lines in each route. For example, in /api/roadmapPlans/search the selector creation process can be moved to a helper method.

2022-08-05 23:59 UTC, Matth-ewe-f commented
Deletion route, tag editing routes, etc. are on a different branch, this one is just the creation route. Take a look at the changes, see if this is better!

2023-03-07 07:24 UTC, closed without merging