Remove pyramid of doom and add tests
uCredit-Dev/uCredit-API pull request #70
Opened 2023-01-02 06:55 UTC by mpark63

** refractoring... ** 
- replace .thens with async/await 
  - make sure to await .save(), and .exec() queries 
- remove mongoose errors 
- make import naming consistent 
- added some more error handling
  - check for missing request fields in all routes (`missingHandler`)
  - add some 404 checking 
- write tests for higher coverage 
  - runs alright individually; npm test though does not work 
- fixed bugs while testing

2023-01-02 07:05 UTC, mpark63 commented
Apologies for big PR. Had to write tests in same branch as async/await as I wanted to make sure no breaking changes were made while removing pyramids of doom! Kindly review.

2023-01-02 19:50 UTC, mattliu-mygit requested changes
Good job!!!! You blew me out of the water!!! This is amazing. Please note comments tho. :)

2023-01-02 19:50 UTC, mattliu-mygit commented on data/updateSIS.js
> +  await course.save();
Are these awaits necessary?

2023-01-02 19:50 UTC, mattliu-mygit commented on routes/planReview.js
> +    const _review = await Reviews
Is this good naming convention?

2023-01-02 19:50 UTC, mattliu-mygit commented on routes/planReview.js
> +    const _review = await Reviews
yes? no? maybe so

2023-01-02 19:50 UTC, mattliu-mygit commented on routes/planReview.js
> +      status: "PENDING",
Usually these constants should be put in an enum.
ie.
const PLAN_STATUS = {pending: "PENDING", review: "PLANREVIEW"}

2023-01-02 19:50 UTC, mattliu-mygit commented on routes/sso.js
> -    privateCert: PvK,
pogger

2023-01-02 19:50 UTC, mattliu-mygit commented on routes/user.js
>  // if (DEBUG) {
We can probably uncomment this now... I don't see any big issues with uncommenting this and it's good.

2023-01-02 19:50 UTC, mattliu-mygit commented on tests/routes/SSO.spec.js
What is the statement and branch coverage?

2023-01-07 05:23 UTC, QinyuanWu approved these changes
Great work Minseo!! These changes are much needed QAQ

2023-01-08 19:13 UTC, mpark63 commented
<img width="940" alt="Screenshot 2023-01-08 at 2 12 41 PM" src="https://user-images.githubusercontent.com/90944895/211214474-401fbbbb-bd3c-48c4-8bc0-1f12f2552710.png">
<img width="404" alt="Screenshot 2023-01-08 at 2 12 53 PM" src="https://user-images.githubusercontent.com/90944895/211214478-bc726783-4fcc-48d7-ba5a-4fd7e817bc82.png">

2023-01-08 22:32 UTC, merged